name: Static Analysis
on: [pull_request, workflow_dispatch]
concurrency:
  group: static-analysis-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  android_lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Lint
        run: ./ci lint
  # Ref: https://github.com/gradle/wrapper-validation-action
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
